#!/usr/bin/env bash
# After configuring domain zone, use this script to output where each subdomain points to

runDig () {
    subarg=$1
    urlarg=$2

    dig "$subarg.$urlarg" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subarg" 'BEGIN

