#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
# request, it returns a page that contains the string
# 'Hello World!'.

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
