#!/usr/bin/env bash
# Affiche le contenu du répertoire courant en format de liste.
# Montre uniquement la partie du nom après le premier tiret.
# N'affiche pas les fichiers cachés.

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
